const BASE = 'Base';

const OWNER_ABOUT = `${BASE}OwnerAbout`;
const WAREHOUSE_ABOUT = `${BASE}WarehouseAbout`;
const HUMAN_RESOURCE = `${BASE}HumanResourceManagement`;
const RULE_BATCH_ATTRIBUTE = `${BASE}RuleBatchAttribute`;

export default {
  OWNER: `${OWNER_ABOUT}Owner`,
  GOODS: `${OWNER_ABOUT}Goods`,
  WAREHOUSE: `${WAREHOUSE_ABOUT}Warehouse`,
  WAREHOUSE_ZONE: `${WAREHOUSE_ABOUT}WarehouseZone`,
  WAREHOUSE_STOREHOUSE: `${WAREHOUSE_ABOUT}WarehouseStoreHouse`,
  WAREHOUSE_LOGICAL_AREA: `${WAREHOUSE_ABOUT}WarehouseLogicalArea`,
  WAREHOUSE_CONTAINER: `${WAREHOUSE_ABOUT}WarehouseContainer`,
  WAREHOUSE_LOADING_PORT: `${WAREHOUSE_ABOUT}WarehouseLoadingPort`,
  WAREHOUSE_DEVICE: `${WAREHOUSE_ABOUT}WarehouseDevice`,
  WAREHOUSE_PDA: `${WAREHOUSE_ABOUT}WarehousePda`,
  WAREHOUSE_FLUENT_RACK: `${WAREHOUSE_ABOUT}WarehouseFluentRack`,
  HUMAN_STAFF_MAGE: `${HUMAN_RESOURCE}StaffMage`,
  HUMAN_POSITION_MAGE: `${HUMAN_RESOURCE}PositionMage`,
  SCHEDULING_PLAN: `${HUMAN_RESOURCE}SchedulingPlan`,
  FLUENT_SCH_PLAN: `${HUMAN_RESOURCE}SchPlan`,
  GOODS_ALLOCATION: `${HUMAN_RESOURCE}GoodsAllocation`,
  RULE_BATCH_ATTRIBUTE: `${RULE_BATCH_ATTRIBUTE}`,
};
